export enum Errors {
  NO_USERNAME_PROVIDED = "No username provided",
  USER_NOT_FOUND = "User not found",
  SOMETHING_WENT_WRONG = "Something went wrong",
  NO_EMAIL_PROVIDED = "No email provided",
  NO_PASSWORD_PROVIDED = "No password provided",
  NO_USERNAME_OR_EMAIL_PROVIDED = "No username or email provided",
  NO_USERNAME_OR_PASSWORD_PROVIDED = "No username or password provided",
  NO_EMAIL_OR_PASSWORD_PROVIDED = "No email or password provided",
  NO_USERNAME_OR_EMAIL_OR_PASSWORD_PROVIDED = "No username or email or password provided",
  USER_ALREADY_EXISTS = "User already exists",
  INVALID_CREDENTIALS = "Invalid credentials",
  INVALID_TOKEN = "Invalid token",
  NO_TOKEN_PROVIDED = "No token provided",
  NO_USER_ID_PROVIDED = "No user id provided",
  NO_USER_FOUND = "No user found",
  NO_USER_ID_OR_TOKEN_PROVIDED = "No user id or token provided",
  INVALID_PASSWORD = "Invalid password",
  ALREADY_FOLLOWING = "Already following",
  NOT_FOLLOWING = "Not following",
  UNAUTHORIZED = "Unauthorized",
  MISSING_FIELDS = "Missing fields",
  NOT_FOUND = "Not found",
  ALREADY_LIKED = "Already liked",
  NOT_LIKED = "Not liked",
}

export enum RESPONSE_TYPES {
  ERROR = "error",
  SUCCESS = "success",
}
